--1
SELECT * FROM SALGRADE;
--2
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM EMP;
--3
SELECT DISTINCT JOB FROM EMP;
--4
SELECT DISTINCT ENAME,(SAL * 12) AS REMUNERATION FROM EMP  WHERE ROWNUM < 15 AND SAL IS NOT NULL;
--5
SELECT  ENAME || ' HAS HELP THE POSITION OF '
            || EMP.JOB || ' IN DEPT '
            || DEPTNO || ' SINCE ' || HIREDATE FROM EMP;
--6
DESCRIBE EMP;
--7
SELECT TO_CHAR(SAL ,'fm999G999G990') AS SALARY,
       TO_DATE(HIREDATE, 'dd/mm/yyyy') AS HIREDATE FROM EMP WHERE SAL Is not null;

----------------------------------------
--1
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
--2
SELECT DEPTNO,DNAME FROM DEPT ORDER BY DNAME ASC;
--3
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20;
--4
SELECT ENAME,JOB FROM EMP WHERE JOB = 'CLERK' AND DEPTNO = 20;
--5
SELECT ENAME FROM EMP WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';
--6
SELECT ENAME,JOB,SAL  FROM EMP WHERE JOB != 'PRESIDENT';
--7
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'yyyy') = 1983;
--8
SELECT SAL*12 AS ANUAL_SAL, COMM FROM EMP
        WHERE JOB = 'SALESMAN' AND SAL > EMP.COMM ORDER BY SAL DESC, ENAME ASC;



