--1
SELECT * FROM SALGRADE;
--2
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM EMP;
--3
SELECT DISTINCT JOB FROM EMP;
--4
SELECT DISTINCT ENAME,(SAL * 12) AS REMUNERATION FROM EMP  WHERE ROWNUM < 15 AND SAL IS NOT NULL;
--5
SELECT  ENAME || ' HAS HELP THE POSITION OF '
            || EMP.JOB || ' IN DEPT '
            || DEPTNO || ' SINCE ' || to_date(HIREDATE,'dd/mm/yyyy') FROM EMP;
--6
DESCRIBE EMP;
--7
SELECT TO_CHAR(SAL ,'fm999G999G990') AS SALARY,
       TO_DATE(HIREDATE, 'dd/mm/yyyy') AS HIREDATE FROM EMP WHERE SAL Is not null;





