CREATE OR REPLACE PROCEDURE PRD_MESSAGES_01(
    PRD_NUM1 NUMBER, PRD_NUMCOL1 OUT MESSAGES_HIENNV.NUMCOL1%type
)
AS
BEGIN
    SELECT NUMCOL1 INTO PRD_NUMCOL1 FROM MESSAGES_HIENNV WHERE NUMCOL1 = PRD_NUM1;
END;

DECLARE
    TEXT200112 NUMBER;
BEGIN
    PRD_MESSAGES_01(24, TEXT200112);
    INSERT INTO MESS_TTT(NUM12001) VALUES (TEXT200112);
END;

SELECT *
FROM MESS_TTT;

select to_char(trunc(current_date), 'dd/MM/yyyy HH24/mi/ss') from DUAL;
