--1
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
--2
SELECT DEPTNO,DNAME FROM DEPT ORDER BY DNAME ASC;
--3
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20;
--4
SELECT ENAME,JOB FROM EMP WHERE JOB = 'CLERK' AND DEPTNO = 20;
--5
SELECT ENAME FROM EMP WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';
--6
SELECT ENAME,JOB,SAL  FROM EMP WHERE JOB != 'PRESIDENT';
--7
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE,'yyyy') = 1983;
--8
SELECT SAL*12 AS ANUAL_SAL, COMM FROM EMP
        WHERE JOB = 'SALESMAN' AND SAL > EMP.COMM ORDER BY SAL DESC, ENAME ASC;